"""add analysis timestamps

Revision ID: 80b65814b509
Revises: 96694c2e0fc9
Create Date: 2026-08-02 20:53:39.296923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b65814b509'
down_revision: Union[str, Sequence[str], None] = '96694c2e0fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('analysis_started_at', sa.DateTime(), nullable=True))
    op.add_column('resumes', sa.Column('analysis_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'analysis_completed_at')
    op.drop_column('resumes', 'analysis_started_at')
    # ### end Alembic commands ###
