"""add resume analysis status

Revision ID: 96694c2e0fc9
Revises: 0f1c7f7f9da7
Create Date: 2026-08-01 02:35:55.200270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96694c2e0fc9'
down_revision: Union[str, Sequence[str], None] = '0f1c7f7f9da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('analysis_status', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_resumes_analysis_status'), 'resumes', ['analysis_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_analysis_status'), table_name='resumes')
    op.drop_column('resumes', 'analysis_status')
    # ### end Alembic commands ###
