name: FastAPI CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: resume_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          - name: Check Environment
            env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5434/resume_db"
        run: |
        echo "DATABASE_URL=$DATABASE_URL"
      - name: Run Database Migrations
        env:
          APP_NAME: "AI Resume Analyzer"
          APP_ENV: "testing"
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5434/resume_db"
          JWT_SECRET_KEY: "test-secret-key"
          JWT_ALGORITHM: "HS256"
          REDIS_URL: "redis://localhost:6379/0"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OLLAMA_HOST: "http://localhost:11434"
        run: |
          alembic upgrade head

      - name: Run Unit Tests
        env:
            APP_NAME: "AI Resume Analyzer"
            APP_ENV: "testing"
            DATABASE_URL: "postgresql://postgres:postgres@localhost:5434/resume_db"
            JWT_SECRET_KEY: "test-secret-key"
            JWT_ALGORITHM: "HS256"
            REDIS_URL: "redis://localhost:6379/0"
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
            OLLAMA_HOST: "http://localhost:11434"
        run: |
          pytest -v

      - name: Build Production Docker Image
        run: |
          docker build \
          -f Dockerfile.prod \
          -t resume-api:${{ github.sha }} .